platform :android do
  lane :upload_to_internal do
    supply(
      json_key_data: ENV["GOOGLE_PLAY_JSON_KEY"],
      package_name: "com.jump.shot.jam.game",
      aab: "build_output/Jump.Shot.Jam_4.aab",
      track: "internal",
      release_status: "completed",
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true
    )
  end
end
